#!/bin/bash
################################################################################
# Copyright 2013-2014 Aerospike, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

if [ ! -f php_aerospike.h ]; then
  echo "This script needs to run inside src/aerospike"
  exit
fi
if [ -x git ]; then
  git clean -fd
else
  rm -f Makefile*
  rm -f ac*m4
  rm -rf autom4te.cache/
  rm -rf build/
  rm -f config.guess
  rm -f config.h*
  rm -f config.log
  rm -f config.nice
  rm -f config.status
  rm -f config.sub
  rm -f configure*
  rm -f .deps
  rm -f install-sh
  rm -f libtool
  rm -f ltmain.sh
  rm -f missing
  rm -f mkinstalldirs
  rm -f run-tests.php
  rm -f tmp-php.ini
  rm -rf .libs/
  test-cleanup
fi

