#!/bin/bash
LOGLEVEL="AS_LOG_LEVEL_OFF"

parse_args () {
    while [[ $# > 1 ]]
    do
        key="$1"
        shift

        case $key in
            -l|--loglevel)
                case "$1" in
                    TRACE|trace)
                        LOGLEVEL="AS_LOG_LEVEL_TRACE"
                        ;;
                    DEBUG|debug)
                        LOGLEVEL="AS_LOG_LEVEL_DEBUG"
                        ;;
                    INFO|info)
                        LOGLEVEL="AS_LOG_LEVEL_INFO"
                        ;;
                    WARN|warn)
                        LOGLEVEL="AS_LOG_LEVEL_WARN"
                        ;;
                    ERROR|error)
                        LOGLEVEL="AS_LOG_LEVEL_ERROR"
                        ;;
                    OFF|off)
                        LOGLEVEL="AS_LOG_LEVEL_OFF"
                        ;;
                    *)
                        echo "Usage:"
                        echo "build -l|--loglevel <ONE AMONG: TRACE, DEBUG, INFO, WARN, ERROR, OFF> [-h|--help]"
                        exit 1
                        ;;
                esac
                shift
                ;;
            -h|--help)
                echo "Usage:"
                echo "build -l|--loglevel <ONE AMONG: TRACE, DEBUG, INFO, WARN, ERROR, OFF> [-h|--help]"
                shift
                ;;
            --default)
                echo "Using default Loglevel."
                LOGLEVEL="AS_LOG_LEVEL_OFF"
                shift
                ;;
            *)
                echo "Usage:"
                echo "build -l|--loglevel <ONE AMONG: TRACE, DEBUG, INFO, WARN, ERROR, OFF> [-h|--help]"
                exit 1
                ;;
        esac
    done
}

if [ -f Makefile ]; then
  make clean
fi
parse_args $@
phpize
./configure "CFLAGS=-g -O3" --enable-aerospike
make clean all CFLAGS=-g EXTRA_INCLUDES+=-D__AEROSPIKE_PHP_CLIENT_LOG_LEVEL__=${LOGLEVEL} -I$CLIENTREPO_3X/include EXTRA_LDFLAGS="-L$CLIENTREPO_3X/lib -laerospike -llua -lrt -lcrypto" 
test-cleanup

